# The name of your workflow
name: IOS

# When should this workflow run?
on:
  pull_request:
    branches:
      - master

# Jobs to perform in this workflow
jobs:
  flutter_test:
    # Name of the job
    name: Run Flutter Test and analyze
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      # Sets up the Flutter SDK
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      # Gets the dependencies and builds the app
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  build_ios:
    name: Build Flutter(ios)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter clean
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v2
        with:
          name: MyApp-iOS
          path: build/ios/iphoneos/app.ipa

      # Package the app into an IPA file

  #      - run: |
  #          flutter build ios --no-codesign --build-name=$GITHUB_SHA --build-number=$GITHUB_RUN_NUMBER
  #          cd build/ios/iphoneos
  #          mkdir Payload
  #          cd Payload
  #          ln -s ../Runner.app
  #          cd ..
  #          zip -r app.ipa Payload

  distribute-ios:
    needs: build_ios # This is important
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: MyApp-iOS
          path: .

      - name: List Contents of Working Directory
        run: ls -al
      # Uploads the app to Firebase App Distribution
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_IOS_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          file: /home/runner/work/flutter_github_action/flutter_github_action/app.ipa


          #      - name: Push to Releases
          #        uses: ncipollo/release-action@v1
          #        with:
          #          artifacts: "build/ios/iphones/app.ipa"
          #          tag: ios.v1.0.${{github.run_number}}
          #          token: ${{secrets.TOKEN}}


